"""
dlt source for ad spend data from CSV flat files.

In production this would pull from a data export API (Google Ads, Meta Ads Manager).
Locally it reads the CSV generated by seeds/generate_ad_spend.py.
"""

import csv
from collections.abc import Iterator
from pathlib import Path

import dlt
from dlt.sources import DltResource


@dlt.source(name="ad_spend_csv")
def ad_spend_source(
    csv_path: str = dlt.config.value,
) -> DltResource:
    """Load ad spend data from CSV export."""
    return _ad_spend_resource(csv_path)


@dlt.resource(
    name="raw_ad_spend",
    write_disposition="replace",
    primary_key=["client_id", "channel", "date"],
)
def _ad_spend_resource(csv_path: str) -> Iterator[dict]:
    """Yield ad spend rows from CSV, casting numeric columns."""
    path = Path(csv_path)
    if not path.exists():
        raise FileNotFoundError(
            f"Ad spend CSV not found at {csv_path}. Run 'make seed' first."
        )
    with open(path, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            yield {
                "client_id": int(row["client_id"]),
                "channel": row["channel"],
                "date": row["date"],
                "spend": float(row["spend"]),
                "impressions": int(row["impressions"]),
                "clicks": int(row["clicks"]),
            }
